- name: ansible to install pymysq
  ansible.builtin.pip: 
    name:
      - PyMySQL
    executable: pip3.9

- name: installing mysql
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: start the service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes
- name: mysql connection to root
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_host: "{{login_host}}"
  ignore_errors: true
  register: mysql_info

- name: mysql_info
  ansible.builtin.debug:
    msg: "{{mysql_info}}"

- name: mysql set root password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql_root_password}}"
  when: mysql_info.failed is true